# Generated by Django 4.2 on 2023-04-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="title",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
