# Generated by Django 4.2 on 2023-04-18 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_remove_bookmark_book_remove_bookmark_marker"),
        ("books_marks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="markers",
            field=models.ManyToManyField(
                related_name="marked_books",
                through="books_marks.BookMark",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="BookMark",
        ),
    ]
