# Generated by Django 4.2 on 2023-04-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="birthdate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="cpf",
            field=models.CharField(max_length=11, null=True),
        ),
    ]
